include:

  - board: nice_nano_v2
    shield: settings_reset
  - board: sofle_left
    # shield: nice_view_adapter nice_view
    shield: nice_view_adapter nice_view_adapter nice_view_gem
    artifact-name: sofle_left_nice_view
  - board: sofle_right
    # shield: nice_view_adapter nice_view_custom
    shield: nice_view_adapter nice_view_adapter nice_view_gem
    artifact-name: sofle_right_nice_view
